### ISSUE TITLE
今天开始使用时突然报错

### ISSUE THREAD

**Issue by Misty02600** [lgc-NB2Dev/nonebot-plugin-ottohzys#2]
已尝试更新插件和重启bot仍报错，看不懂是插件问题还是onebot的问题

```
03-11 13:23:22 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_ottohzys.__main__, lineno=64)
03-11 13:23:22 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_ottohzys.__main__, lineno=64) running complete
03-11 13:23:22 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_ottohzys.__main__, lineno=64) failed.
Traceback (most recent call last):
  File "C:\Bot\LittlePaimon\bot.py", line 37, in <module>
    nonebot.run(app="__mp_main__:app", access_log=False)
  File "C:\Bot\LittlePaimon\.venv\lib\site-packages\nonebot\__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "C:\Bot\LittlePaimon\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Bot\LittlePaimon\.venv\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "C:\Bot\LittlePaimon\.venv\lib\site-packages\uvicorn\server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Bot\LittlePaimon\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Bot\LittlePaimon\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Bot\LittlePaimon\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Bot\LittlePaimon\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
    await handler(
  File "C:\Bot\LittlePaimon\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Bot\LittlePaimon\.venv\lib\site-packages\nonebot_plugin_ottohzys\__main__.py", line 103, in _
    await UniMessage.voice(raw=voice).send()
  File "C:\Bot\LittlePaimon\.venv\lib\site-packages\nonebot_plugin_alconna\uniseg\message.py", line 913, in send
    res = await fn.send_to(target, bot, msg)
  File "C:\Bot\LittlePaimon\.venv\lib\site-packages\nonebot_plugin_alconna\uniseg\adapters\onebot11\exporter.py", line 127, in send_to
    return await bot.send_msg(message_type="group", group_id=int(target.id), message=message)
  File "C:\Bot\LittlePaimon\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "C:\Bot\LittlePaimon\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Bot\LittlePaimon\.venv\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 144, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "C:\Bot\LittlePaimon\.venv\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(data=None, echo='4', message='empty message', msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='empty message')
```

**Comment by lgc2333** [comment]
尝试降级插件，看看可不可以

```bash
pip install nonebot-plugin-ottohzys==0.1.2
```

**Comment by Misty02600** [comment]
> 尝试降级插件，看看可不可以
> 
> ```shell
> pip install nonebot-plugin-ottohzys==0.1.2
> ```

已降级，还是相同的报错

**Comment by lgc2333** [comment]
那就是协议端的锅了，你用的是什么协议端

**Comment by Misty02600** [comment]
> 那就是协议端的锅了，你用的是什么协议端

是gocq，检查了一下确实有提示语音上传失败

**Comment by lanqianlv** [comment]
同样异常，我是拉格朗日的ntqq

**Comment by lgc2333** [comment]
> 同样异常，我是拉格朗日的ntqq

拉格朗日用不了，目前拉格朗日只能发mp3语音好像

**Comment by lgc2333** [comment]
> > 那就是协议端的锅了，你用的是什么协议端
> 
> 是gocq，检查了一下确实有提示语音上传失败

看一下报错内容

**Comment by lanqianlv** [comment]
> > 同样异常，我是拉格朗日的ntqq
> 
> 拉格朗日用不了，目前拉格朗日只能发mp3语音好像

😭

**Comment by Misty02600** [comment]
> > > 那就是协议端的锅了，你用的是什么协议端
> > 
> > 
> > 是gocq，检查了一下确实有提示语音上传失败
> 
> 看一下报错内容

今天突然又可以发出来了（（，抱歉，可以关掉了
