### ISSUE TITLE
更新 Resource 下载地址

### ISSUE THREAD

**Issue by Rain-0x01-39** [lgc-NB2Dev/nonebot-plugin-ottohzys#6]
```sh
07-07 22:18:05 [INFO] nonebot_plugin_ottohzys | Resource not found, trying to download, please wait...
07-07 22:18:06 [ERROR] nonebot_plugin_ottohzys | Failed to download resources, please download manually
07-07 22:18:06 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\rain1\AppData\Roaming\Python\Python310\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Program Files\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "C:\Users\rain1\AppData\Roaming\Python\Python310\site-packages\nonebot\drivers\fastapi.py", line 153, in _lifespan_manager
    await self._lifespan.startup()
  File "C:\Users\rain1\AppData\Roaming\Python\Python310\site-packages\nonebot\internal\driver\_lifespan.py", line 42, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "C:\Users\rain1\AppData\Roaming\Python\Python310\site-packages\nonebot\internal\driver\_lifespan.py", line 36, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "C:\Users\rain1\AppData\Roaming\Python\Python310\site-packages\nonebot_plugin_ottohzys\resource.py", line 111, in _
    await check_and_download()
  File "C:\Users\rain1\AppData\Roaming\Python\Python310\site-packages\nonebot_plugin_ottohzys\resource.py", line 87, in check_and_download
    await download_resource()
  File "C:\Users\rain1\AppData\Roaming\Python\Python310\site-packages\nonebot_plugin_ottohzys\resource.py", line 63, in download_resource
    resp.raise_for_status()
  File "C:\Users\rain1\AppData\Roaming\Python\Python310\site-packages\httpx\_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://hub.gitmirror.com/https://github.com/HanaYabuki/otto-hzys/archive/refs/heads/master.zip'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

07-07 22:18:06 [ERROR] uvicorn | Application startup failed. Exiting.
```

看起来是下载文件出错了。建议改为
```
https://mirror.ghproxy.com/https://github.com/HanaYabuki/otto-hzys/archive/refs/heads/master.zip
```

**Comment by SZ2528** [comment]
手动下载完成后文件扔哪

**Comment by lgc2333** [comment]
#5

https://github.com/lgc-NB2Dev/nonebot-plugin-ottohzys/compare/v0.2.1...v0.2.1.post1
