### ISSUE TITLE
[bug] 也许是依赖问题

### ISSUE THREAD

**Issue by flipwind** [lgc-NB2Dev/nonebot-plugin-ottohzys#7]
```log
07-24 05:20:45 [ERROR] nonebot | Failed to import "nonebot_plugin_ottohzys"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\napcat\.venv\Lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\napcat\.venv\Lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\napcat\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "C:\napcat\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\napcat\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\napcat\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\napcat\.venv\Lib\site-packages\nonebot_plugin_ottohzys\__init__.py", line 5, in <module>
    from . import __main__ as __main__  # noqa: E402
  File "C:\napcat\.venv\Lib\site-packages\nonebot_plugin_ottohzys\__main__.py", line 8, in <module>
    from .hzys import generate
  File "C:\napcat\.venv\Lib\site-packages\nonebot_plugin_ottohzys\hzys.py", line 11, in <module>
    import psola
  File "C:\napcat\.venv\Lib\site-packages\psola\__init__.py", line 1, in <module>
    from .core import *
  File "C:\napcat\.venv\Lib\site-packages\psola\core.py", line 9, in <module>
    from parselmouth import Data, praat, Sound
ImportError: DLL load failed while importing parselmouth: 找不到指定的模块。
```

python 3.12
nonebot
windows server 2022

rt, 很奇怪

**Comment by lgc2333** [comment]
尝试安装vcredist：https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version
仍不行请尝试python3.11
